import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { hasInvoiceUnlock } from "@/lib/invoice-auth";
import { prisma } from "@/lib/prisma";
import { calculateClientPriceCents } from "@/lib/pricing";
import { InvoiceDocument, type InvoiceLineItem } from "@/components/invoice/invoice-document";

export default async function InvoicePrintPage({
  params,
  searchParams,
}: {
  params: Promise<{ batchNumber: string }>;
  searchParams: Promise<{ client?: string; invoiceNo?: string }>;
}) {
  const session = await getSession();
  if (!session || session.role !== "admin") {
    redirect("/admin");
  }
  if (!(await hasInvoiceUnlock())) {
    redirect("/admin/invoices");
  }

  const { batchNumber: batchNumberParam } = await params;
  const { client, invoiceNo } = await searchParams;
  const batchNumber = Number(batchNumberParam);

  const submissions = await prisma.videoSubmission.findMany({
    where: { batchNumber },
    include: { style: true },
    orderBy: { submittedAt: "asc" },
  });

  const items: InvoiceLineItem[] = submissions.map((s) => {
    const rate = s.style.clientRatePerMinuteCents;
    const amountCents =
      rate == null
        ? null
        : calculateClientPriceCents(s.durationMinutes, {
            clientRatePerMinuteCents: rate,
            clientPerMinuteIncrementCents: s.style.clientPerMinuteIncrementCents,
            clientBaseSeconds: s.style.clientBaseSeconds,
            clientOverageUnitSeconds: s.style.clientOverageUnitSeconds,
            clientOverageGraceSeconds: s.style.clientOverageGraceSeconds,
            clientOverageProportional: s.style.clientOverageProportional,
          });
    return {
      title: s.title,
      detail: s.styleName + (s.clientOrProject ? ` · ${s.clientOrProject}` : ""),
      durationMinutes: s.durationMinutes,
      amountCents,
    };
  });

  const totalCents = items.reduce((sum, i) => sum + (i.amountCents ?? 0), 0);

  return (
    <InvoiceDocument
      fromName="AHMD.GPT"
      toName={client}
      invoiceNumber={invoiceNo}
      dateLabel={new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })}
      batchLabel={`Batch ${batchNumber}`}
      items={items}
      totalCents={totalCents}
      currency="USD"
      footerNote="Generated by AHMD.GPT Editor Ops."
    />
  );
}
